### ISSUE TITLE
can ARM machine install this module？

### ISSUE THREAD

**Issue by unavailable-2374** [jeffdaily/parasail-python#71]
hi
I was trying to install it on my arm machine, but it shows that parasail/libparasail.so not found, attempting to build.
And try to download the latest parasail master.

Unfortunately, the download always get wrong, like "URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))"
when I try to add "import ssl" and "ssl._create_default_https_context = ssl._create_unverified_context"
it show's "RemoteDisconnected('Remote end closed connection without response')"

Is there anything i do wrong? or it just not ready for arm machine.

Thank you~

**Comment by jeffdaily** [comment]
Yes, the C parasail library is ready for arm and supports neon ISA.  The github actions CI builds for arm.

The setup.py is trying to perform the download and build of the C parasail libparasail.so and put it in the right place for the python bindings to find at runtime.  You can do the download and build yourself and then place the resulting libparasail.so under the parasail directory of your parasail-python sources and run setup.py that way.

The issue is the ssl cert failure, not parasail.

**Comment by unavailable-2374** [comment]
> 

thank you Jef

I installed it yesterday night, sorry that i forgot to cancel my question 

hope you get a good day!

cao
